CREATE TABLE IF NOT EXISTS productos (
    id SERIAL PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    precio DECIMAL(10,2) NOT NULL
);

ALTER TABLE productos
ADD COLUMN IF NOT EXISTS cantidad INT DEFAULT 0;

ALTER TABLE productos
ADD COLUMN IF NOT EXISTS tienda VARCHAR(100) DEFAULT '';    